name: Feature Request
description: Suggest an idea for this project
labels: 'Feature'
body:
- type: textarea
  attributes:
    label: Feature Description
    placeholder: "Describe a feature you'd like us to add. If it's not obvious, explain why this feature is awesome. Note that feature requests must be specific and measurable."
- type: textarea
  attributes:
    label: Bug Description
    placeholder: |
      Describe what problem occurred and what you expected to happen instead.
  
      1. To reproduce this, open file '...'
      2. Click on '....'
      3. See error
- type: textarea
  attributes:
    label: Attachments
    description: "Private files can be uploaded to https://ifcopenshell.org/upload.html - only viewed by core developers and will be deleted afterwards. Please submit your report first then upload private files afterwards."
    placeholder: "If applicable, add screenshots to help explain your problem. Please also drag-drop any files necessary to show the error (rename the file extension from .ifc to .txt to upload)."
- type: textarea
  attributes:
    label: Debug and Error Output
    description: "If this is in Bonsai, paste the output from the Copy Debug Information option in Bonsai. It can be found under Quality and Coordination -> Quality Control -> Debug. If this is a general software issue, if relevant include details about IfcOpenShell version, operating system, Python version, etc."
    render: yes
